server:
  port: 8096
  session-timeout: 1800

# 应用信息
app:
  app-name: media
  app-host: http://media-ops-backend.com
  allow-generate-api: true
  allow-cross-domain-access: true
  # 开发dev 测试test  生产 master
  env: dev

# 对象存储配置
oss:
  accessKeyId: LTAInqWcAs3HAoqe
  accessKeySecret: 61tY3ImkyhZ6xzbNtS85O0URWNwrOs
  upload-endpoint: http://oss-cn-beijing.aliyuncs.com
  download-endpoint: http://share-app2.oss-cn-beijing.aliyuncs.com
  bucketName: share-app2
  # 下载地址的有效时长，单位为ms，默认为半小时
  download-url-expiration: 1800000

spring:
  main:
    banner-mode: console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 10Mb
  datasource:
    name: datasource
    initialize: false
#    url: jdbc:mysql://rm-bp1duiwgiw1zw5jck9o.mysql.rds.aliyuncs.com:3306/share_app2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
#    username: meiyoushop
#    password: nblc123!@#
    url: jdbc:mysql://119.23.29.186:3306/share_app2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    max-active: 2
    max-idle: 2
    min-idle: 2
    initial-size: 2
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: false
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml


logging:
  path: /base-web-log

# 缓存配置
memcached:
#  servers: 139.129.116.62:11211
#  username: root
#  password: YwjX2NhL62
#  servers: m-wz908bf90ddf43f4.memcache.rds.aliyuncs.com:11211
#  username: m-wz908bf90ddf43f4
#  password: Json2018
#  needAuth: false
  servers: 119.23.29.186:11211
  username: root
  password: YwjX2NhL62
# 系统配置（包含：短信等）
sms:
  sign: zhenpinApp
  url: dysmsapi.aliyuncs.com
  accessKeyID: LTAIWHM5uW8kkMBl
  accessKeySecret: qY4lFzX7nabcG5aK9YqyK7Qxi7tJ3f
  templateCode: SMS_137620041



#分享文章/商品访问域名
shareUrl:
  articleUrl: http://localhost:8083/ShareDate/articleShareDataRecord.do
  commodityUrl: